# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.define :nox do |box|
    # Every Vagrant virtual environment requires a box to build off of.
    box.vm.box = "precise64"
    # The url from where the 'config.vm.box' box will be fetched if it
    # doesn't already exist on the user's system.
    box.vm.box_url = "http://files.vagrantup.com/precise64.box"
    
    # Boot with a GUI so you can see the screen. (Default is headless)
    #box.vm.boot_mode = :gui
    # add a hostonly network if desired
    #box.vm.network :hostonly, "33.33.33.151"

    # box.vm.provision :puppet do |puppet|
    #   puppet.manifests_path = "puppetmanifests"
    #   puppet.manifest_file = "raspberry-nox.pp"
    #   puppet.module_path = "modules"
    #   puppet.options = ["--verbose", "--debug"]
    # end
  end
end

Vagrant.configure("2") do |config|
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.synced_folder "../../", "/var/pasori/",
    mount_options: ['dmode=777', 'fmode=776']
  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.network "forwarded_port", guest: 80, host: 8080
end